<?php

use Drupal\api_consumer\PokemonService;

/**
 * Implements hook_theme().
 */
function api_consumer_theme($existing, $type, $theme, $path)
{
    return [
        'node__pokemon__full' => [
            'template' => 'node--pokemon--full',
            'base hook' => 'node'
        ],
    ];
}

/**
 * Implements hook_cron().
 */
function api_consumer_cron()
{
    $pokemons_first_call = PokemonService::BeginEntry();
    if ($pokemons_first_call != FALSE) {
        PokemonService::createPokemonsFromCron($pokemons_first_call);
    }

}
